Update to new bedtool intersect query
weng-lab/SCREEN2.0 pull request #363
Opened 2024-07-09 17:38 UTC by GannaMohit

Using GraphQL API instead of the old one to work with v4 cCREs.

2024-07-09 17:40 UTC, NishiPhalke commented on screen2.0/src/app/_mainsearch/bedupload.tsx
> +import { log } from "console"
Is this needed ?

2024-07-09 17:41 UTC, NishiPhalke commented on screen2.0/src/app/_mainsearch/bedupload.tsx
> +            console.log(data);
remove console.log

2024-07-09 18:30 UTC, jpfisher72 requested changes

2024-07-09 18:30 UTC, jpfisher72 commented on screen2.0/src/app/_mainsearch/bedupload.tsx
Can you support optional file headers? See https://en.wikipedia.org/wiki/BED_(file_format)#Header

Headers can start with "browser", "track", or "#", and there can be zero to multiple lines of headers

Getting following when trying to intersect file with commented header:
Unable to detect format from ['# chr', 'start', 'end', 'acccession', 'classification', 'DNase_z-score', 'ATAC_z-score', 'CTCF_z-score', 'H3K27ac_z-score', 'H3K4me3_z-score', 'primate_conservation', 'mammal_conservation', 'vertebrate_conservation', 'distance_protein_coding', 'distance_all', 'CTCF-ChIAPET', 'RNAPII-ChIAPET']

2024-07-11 15:13 UTC, jpfisher72 approved these changes

2024-07-11 15:31 UTC, merged